import Link from "next/link";
import { notFound } from "next/navigation";
import { ToggleTask, Starter } from "@/features/planning/components/check-actions";
import { deriveDueState, safeBookingUrl } from "@/features/planning/helpers";
import { getOwnedPlanning } from "@/features/planning/queries";
import { todayInLisbon } from "@/features/trips/lifecycle";
import { getOwnedTrip } from "@/features/trips/queries";
export default async function PlanningPage({ params }: PageProps<"/trips/[tripId]/planning">) {  
const { tripId } = await params, [trip, data] = await Promise.all([getOwnedTrip(tripId), getOwnedPlanning(tripId)]); if (!trip || !data) notFound(); const today = todayInLisbon(); return (
    <main className="min-h-screen bg-background px-5 py-8 sm:px-8 lg:px-12"><div className="mx-auto max-w-6xl"><Link href={`/trips/${tripId}`}>← Voltar à viagem</Link>
      <header className="my-8"><p className="text-xs font-semibold uppercase tracking-[.18em] text-muted-foreground">Reservas e checklist</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Preparar {trip.name}</h1></header>
      <div className="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]">
        <section className="min-w-0 rounded-feature border border-border bg-surface p-5 sm:p-6"><div className="flex flex-wrap justify-between gap-3"><h2 className="text-2xl font-semibold">Reservas</h2><Link href={`/trips/${tripId}/planning/reservations/new`} className="rounded-control bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">Adicionar reserva</Link></div><div className="mt-6 grid gap-4">{data.reservations.filter(x => !x.archivedAt).map(r => <article key={r.id} className="rounded-card border border-border bg-card p-5"><p className="text-xs font-semibold uppercase text-muted-foreground">{r.type} · {r.status}</p><h3 className="mt-2 font-semibold">{r.title}</h3>{r.confirmationCode ? <code className="mt-2 block select-all break-all rounded bg-muted p-2">{r.confirmationCode}</code> : null}{r.bookingUrl && safeBookingUrl(r.bookingUrl) ? <a href={safeBookingUrl(r.bookingUrl)!} target="_blank" rel="noreferrer" className="mt-2 block underline">Abrir reserva</a> : null}{r.needsReview ? <p className="mt-2 text-sm text-warning">Rever associação ou datas.</p> : null}<Link href={`/trips/${tripId}/planning/reservations/${r.id}/edit`} className="mt-3 inline-block text-sm font-semibold underline">Editar</Link></article>)}{!data.reservations.length ? <p className="rounded-card border border-dashed border-border p-6 text-sm leading-6 text-muted-foreground">Mantenha hotéis, restaurantes e referências de reserva num só lugar.</p> : null}</div></section>

        <section className="min-w-0 rounded-feature border border-border bg-surface p-5 sm:p-6"><div className="flex flex-wrap justify-between gap-3"><h2 className="text-2xl font-semibold">Checklist</h2><div className="flex flex-wrap gap-2"><Starter tripId={tripId} /><Link href={`/trips/${tripId}/planning/checklist/new`} className="rounded-control bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">Adicionar tarefa</Link></div></div><div className="mt-6 space-y-3">{data.checklist.map(item => { const due = deriveDueState(item, today); return <article key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-card border border-border bg-card p-4"><div><p className="font-semibold">{item.title}</p><p className="text-sm text-muted-foreground">{item.category}{item.dueDate ? ` · ${item.dueDate} · ${due}` : ""}{item.needsReview ? " · Rever destino" : ""}</p><Link href={`/trips/${tripId}/planning/checklist/${item.id}/edit`} className="text-xs underline">Editar</Link></div><ToggleTask tripId={tripId} itemId={item.id} completed={item.isCompleted} /></article> })}</div></section>
      </div></div></main>
  );
}
