"use client";
import { useActionState,useEffect,useRef,useState } from "react";
import { SUPPORTED_CURRENCIES } from "@/features/auth/options";
import type { RouteData } from "@/features/route/types";
import { minorUnitsToInput } from "@/features/trips/money";
import type { CurrencyCode,Trip } from "@/features/trips/types";
import { createActualAction,createAdjustmentAction,createPaymentAction,saveCostAction } from "../actions";
import type { ActualExpense,CostItem,FinanceActionState,Payment } from "../types";
const input="h-12 w-full rounded-control border border-input bg-card px-4 outline-none focus:border-ring";
const initial:FinanceActionState={status:"idle"};
type Common={trip:Trip;route:RouteData;categories:{id:string;name:string}[]};
function RequestId(){const input=useRef<HTMLInputElement>(null);useEffect(()=>{if(input.current)input.current.value=crypto.randomUUID();},[]);return <input ref={input} type="hidden" name="requestId" defaultValue=""/>;}
function ErrorMessage({state}:{state:FinanceActionState}){return state.message?<p role="alert" className="rounded-control bg-destructive-muted p-4 text-sm text-destructive">{state.message}</p>:null;}
function Field({name,label,type="text",defaultValue="",required=false}:{name:string;label:string;type?:string;defaultValue?:string;required?:boolean}){return <div><label htmlFor={name} className="mb-2 block text-sm font-medium">{label}{required?" *":""}</label><input id={name} name={name} type={type} defaultValue={defaultValue} required={required} className={input}/></div>}
function Scope({route,initialType="trip",initialId=""}:{route:RouteData;initialType?:string;initialId?:string}){const[type,setType]=useState(initialType);return <div className="grid gap-4 sm:grid-cols-2"><div><label className="mb-2 block text-sm font-medium" htmlFor="scopeType">Associação</label><select className={input} id="scopeType" name="scopeType" value={type} onChange={e=>setType(e.target.value)}><option value="trip">Toda a viagem</option><option value="stop">Destino</option><option value="travel_leg">Transporte</option></select></div><div><label className="mb-2 block text-sm font-medium" htmlFor="scopeId">Elemento</label><select className={input} id="scopeId" name="scopeId" defaultValue={initialId} disabled={type==="trip"}><option value="">Selecione</option>{type==="stop"?route.stops.map(s=><option key={s.id} value={s.id}>{s.placeName}</option>):route.legs.map(l=><option key={l.id} value={l.id}>{l.operator||l.mode}</option>)}</select></div></div>}
function Money({prefix,label,baseCurrency,initialAmount="",initialCurrency,initialBase=""}:{prefix:string;label:string;baseCurrency:CurrencyCode;initialAmount?:string;initialCurrency?:CurrencyCode;initialBase?:string}){const[currency,setCurrency]=useState(initialCurrency??baseCurrency),key=(suffix:string)=>prefix?`${prefix}${suffix[0].toUpperCase()}${suffix.slice(1)}`:suffix;return <fieldset className="rounded-card border border-border p-4"><legend className="px-2 text-sm font-semibold">{label}</legend><div className="grid gap-4 sm:grid-cols-3"><Field name={key("amount")} label="Valor original" defaultValue={initialAmount}/><div><label className="mb-2 block text-sm font-medium" htmlFor={key("currency")}>Moeda</label><select className={input} id={key("currency")} name={key("currency")} value={currency} onChange={e=>setCurrency(e.target.value as CurrencyCode)}>{SUPPORTED_CURRENCIES.map(c=><option key={c}>{c}</option>)}</select></div>{currency!==baseCurrency?<Field name={key("baseAmount")} label={`Valor confirmado em ${baseCurrency}`} defaultValue={initialBase}/>:<input type="hidden" name={key("baseAmount")} value=""/>}</div></fieldset>}

export function CostForm({trip,route,categories,cost}:{trip:Trip;route:RouteData;categories:{id:string;name:string}[];cost?:CostItem}){const action=saveCostAction.bind(null,trip.id,cost?.id),[state,formAction,pending]=useActionState(action,initial);return <form action={formAction} className="space-y-6"><RequestId/><Field name="title" label="Título" defaultValue={cost?.title} required/><div><label className="mb-2 block text-sm font-medium" htmlFor="categoryId">Categoria *</label><select className={input} name="categoryId" id="categoryId" defaultValue={cost?.categoryId} required>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><Scope route={route} initialType={cost?.scopeType} initialId={cost?.stopId??cost?.travelLegId??""}/><Money prefix="estimated" label="Estimado (opcional)" baseCurrency={trip.baseCurrency} initialAmount={cost?.estimatedOriginalMinor&&cost.estimatedCurrency?minorUnitsToInput(cost.estimatedOriginalMinor,cost.estimatedCurrency):""} initialCurrency={cost?.estimatedCurrency??trip.baseCurrency} initialBase={cost?.estimatedBaseMinor?minorUnitsToInput(cost.estimatedBaseMinor,trip.baseCurrency):""}/><Money prefix="committed" label="Comprometido/reservado (opcional)" baseCurrency={trip.baseCurrency} initialAmount={cost?.committedOriginalMinor&&cost.committedCurrency?minorUnitsToInput(cost.committedOriginalMinor,cost.committedCurrency):""} initialCurrency={cost?.committedCurrency??trip.baseCurrency} initialBase={cost?.committedBaseMinor?minorUnitsToInput(cost.committedBaseMinor,trip.baseCurrency):""}/><div><label className="mb-2 block text-sm font-medium" htmlFor="notes">Notas</label><textarea className="min-h-28 w-full rounded-control border border-input p-4" id="notes" name="notes" defaultValue={cost?.notes??""}/></div><ErrorMessage state={state}/><button disabled={pending} className="rounded-full bg-primary px-6 py-3 text-sm font-semibold text-primary-foreground disabled:opacity-50">{pending?"A guardar…":"Guardar custo"}</button></form>}

export function TransactionForm({kind,trip,route,categories,costs,initialCostId=""}:{kind:"payment"|"actual";costs:CostItem[];initialCostId?:string}&Common){const action=kind==="payment"?createPaymentAction.bind(null,trip.id):createActualAction.bind(null,trip.id),[state,formAction,pending]=useActionState(action,initial),[linked,setLinked]=useState(initialCostId||(kind==="payment"?costs[0]?.id??"":""));return <form action={formAction} className="space-y-6"><RequestId/><div><label className="mb-2 block text-sm font-medium" htmlFor="costItemId">Custo planeado {kind==="actual"?"(opcional)":"*"}</label><select className={input} id="costItemId" name="costItemId" value={linked} onChange={e=>setLinked(e.target.value)} required={kind==="payment"}><option value="">Sem custo planeado</option>{costs.filter(c=>!c.archivedAt).map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></div>{kind==="actual"&&!linked?<><Field name="title" label="Descrição" required/><div><label className="mb-2 block text-sm font-medium" htmlFor="categoryId">Categoria *</label><select className={input} id="categoryId" name="categoryId" required>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><Scope route={route}/></>:<><input type="hidden" name="title"/><input type="hidden" name="categoryId"/><input type="hidden" name="scopeType" value="trip"/><input type="hidden" name="scopeId"/></>}<Money prefix="" label={kind==="payment"?"Pagamento":"Despesa real"} baseCurrency={trip.baseCurrency}/><Field name="date" label="Data" type="date" required/><Field name="notes" label="Notas"/><ErrorMessage state={state}/><button disabled={pending} className="rounded-full bg-primary px-6 py-3 text-sm font-semibold text-primary-foreground">{pending?"A guardar…":"Registar"}</button></form>}

export function AdjustmentForm({trip,payment,actual}:{trip:Trip;payment?:Payment;actual?:ActualExpense}){const[state,action,pending]=useActionState(createAdjustmentAction.bind(null,trip.id),initial),target=payment??actual;if(!target)return null;return <form action={action} className="space-y-6"><RequestId/><input type="hidden" name="paymentId" value={payment?.id??""}/><input type="hidden" name="actualExpenseId" value={actual?.id??""}/><p className="rounded-control bg-warning-muted p-4 text-sm">O original é preservado. Este registo será guardado como ajuste negativo em {target.currency}.</p><Field name="amount" label={`Valor do reembolso (${target.currency})`} required/>{target.currency!==trip.baseCurrency?<Field name="baseAmount" label={`Valor confirmado em ${trip.baseCurrency}`} required/>:<input type="hidden" name="baseAmount"/>}<Field name="date" label="Data do ajuste" type="date" required/><Field name="notes" label="Motivo" required/><ErrorMessage state={state}/><button disabled={pending} className="rounded-full bg-primary px-6 py-3 text-sm font-semibold text-primary-foreground">Registar ajuste</button></form>}
