"use server";
import { revalidatePath } from "next/cache";import { redirect } from "next/navigation";import type { z } from "zod";
import { getOwnedRoute } from "@/features/route/queries";import { currencyMinorDigits } from "@/features/trips/money";import { getOwnedTrip,requireTripUser } from "@/features/trips/queries";import type { CurrencyCode } from "@/features/trips/types";
import { decimalRatio } from "./calculations";import { adjustmentSchema,categorySchema,costSchema,moneyValues,transactionSchema,uuid } from "./schemas";import { getOwnedCost,getOwnedFinance } from "./queries";import type { FinanceActionState,FinancialScope } from "./types";
const fieldErrors=(error:z.ZodError)=>Object.fromEntries(error.issues.map(issue=>[String(issue.path[0]??"form"),issue.message]));
const financePath=(tripId:string)=>`/trips/${tripId}/finance`;
const value=(data:FormData,key:string)=>String(data.get(key)??"");
const fields=(data:FormData,keys:string[])=>Object.fromEntries(keys.map(key=>[key,value(data,key)]));
const moneyPayload=(money:{original:bigint;currency:CurrencyCode;base:bigint;baseCurrency:CurrencyCode})=>({original:money.original.toString(),currency:money.currency,base:money.base.toString(),rate:money.currency===money.baseCurrency?"1":decimalRatio(money.base,money.original,currencyMinorDigits(money.baseCurrency),currencyMinorDigits(money.currency))});
async function context(tripId:string){if(!uuid.safeParse(tripId).success)return null;const [trip,route,finance]=await Promise.all([getOwnedTrip(tripId),getOwnedRoute(tripId),getOwnedFinance(tripId)]);return trip&&route&&finance?{trip,route,finance}:null;}
function validScope(scopeType:FinancialScope,scopeId:string,route:NonNullable<Awaited<ReturnType<typeof getOwnedRoute>>>){return scopeType==="trip"||(scopeType==="stop"?route.stops.some(s=>s.id===scopeId):route.legs.some(l=>l.id===scopeId));}
function scopePayload(type:FinancialScope,id:string){return{scope_type:type,stop_id:type==="stop"?id:null,travel_leg_id:type==="travel_leg"?id:null};}
function dbError(message:string):FinanceActionState{return{status:"error",message};}

export async function saveCostAction(tripId:string,costId:string|undefined,_state:FinanceActionState,data:FormData):Promise<FinanceActionState>{
 const raw=fields(data,["title","categoryId","scopeType","scopeId","estimatedAmount","estimatedCurrency","estimatedBaseAmount","committedAmount","committedCurrency","committedBaseAmount","notes","requestId"]),parsed=costSchema.safeParse(raw);if(!parsed.success)return{status:"error",fieldErrors:fieldErrors(parsed.error)};
 const ctx=await context(tripId);if(!ctx)return dbError("Viagem não encontrada.");if(!validScope(parsed.data.scopeType,parsed.data.scopeId,ctx.route))return dbError("A associação financeira não pertence a esta viagem.");if(!ctx.finance.categories.some(c=>c.id===parsed.data.categoryId&&c.archivedAt===null))return dbError("Categoria indisponível.");
 const estimate=moneyValues({amount:parsed.data.estimatedAmount,currency:parsed.data.estimatedCurrency,baseAmount:parsed.data.estimatedBaseAmount},ctx.trip.baseCurrency,false),committed=moneyValues({amount:parsed.data.committedAmount,currency:parsed.data.committedCurrency,baseAmount:parsed.data.committedBaseAmount},ctx.trip.baseCurrency,false);
 if(parsed.data.estimatedAmount&&!estimate)return dbError("O valor estimado ou a conversão não é válido.");if(parsed.data.committedAmount&&!committed)return dbError("O valor comprometido ou a conversão não é válido.");
 const ep=estimate?moneyPayload(estimate):null,cp=committed?moneyPayload(committed):null,payload={trip_id:tripId,category_id:parsed.data.categoryId,title:parsed.data.title,...scopePayload(parsed.data.scopeType,parsed.data.scopeId),estimated_original_minor:ep?.original??null,estimated_currency:ep?.currency??null,estimated_base_minor:ep?.base??null,estimated_conversion_rate:ep?.rate??null,committed_original_minor:cp?.original??null,committed_currency:cp?.currency??null,committed_base_minor:cp?.base??null,committed_conversion_rate:cp?.rate??null,notes:parsed.data.notes};
 const{supabase}=await requireTripUser();if(costId){if(!await getOwnedCost(tripId,costId))return dbError("Custo não encontrado.");const{data:saved,error}=await supabase.from("cost_items").update(payload).eq("id",costId).eq("trip_id",tripId).select("id").maybeSingle();if(error||!saved)return dbError("Não foi possível guardar o custo.");}else{const{data:saved,error}=await supabase.from("cost_items").insert({...payload,create_request_id:parsed.data.requestId}).select("id").maybeSingle();if(error?.code==="23505")redirect(`${financePath(tripId)}?costAdded=1`);if(error||!saved)return dbError("Não foi possível criar o custo.");}
 revalidatePath(financePath(tripId));redirect(`${financePath(tripId)}?costSaved=1`);
}

export async function archiveCostAction(tripId:string,costId:string,_state:FinanceActionState):Promise<FinanceActionState>{const cost=await getOwnedCost(tripId,costId);if(!cost)return dbError("Custo não encontrado.");const{supabase}=await requireTripUser();const{error}=await supabase.from("cost_items").update({archived_at:cost.archivedAt?null:new Date().toISOString()}).eq("id",costId).eq("trip_id",tripId);if(error)return dbError("Não foi possível alterar o custo.");revalidatePath(financePath(tripId));redirect(`${financePath(tripId)}?costSaved=1`);}

export async function createPaymentAction(tripId:string,_state:FinanceActionState,data:FormData):Promise<FinanceActionState>{return createTransaction("payment",tripId,data);}
export async function createActualAction(tripId:string,_state:FinanceActionState,data:FormData):Promise<FinanceActionState>{return createTransaction("actual",tripId,data);}
async function createTransaction(kind:"payment"|"actual",tripId:string,data:FormData):Promise<FinanceActionState>{const raw=fields(data,["costItemId","categoryId","title","scopeType","scopeId","amount","currency","baseAmount","date","notes","requestId"]),parsed=transactionSchema.safeParse(raw);if(!parsed.success)return{status:"error",fieldErrors:fieldErrors(parsed.error)};const ctx=await context(tripId);if(!ctx)return dbError("Viagem não encontrada.");if(kind==="payment"&&parsed.data.date>new Date().toISOString().slice(0,10))return dbError("Um pagamento realizado não pode ter uma data futura.");const amount=moneyValues({amount:parsed.data.amount,currency:parsed.data.currency,baseAmount:parsed.data.baseAmount},ctx.trip.baseCurrency,true);if(!amount)return dbError("O valor ou a conversão não é válido.");const mp=moneyPayload(amount),{supabase}=await requireTripUser();let result;
 if(kind==="payment"){if(!ctx.finance.costs.some(c=>c.id===parsed.data.costItemId))return dbError("Custo não encontrado.");result=await supabase.from("payments").insert({trip_id:tripId,cost_item_id:parsed.data.costItemId,amount_original_minor:mp.original,currency:mp.currency,base_amount_minor:mp.base,conversion_rate:mp.rate,paid_on:parsed.data.date,notes:parsed.data.notes,request_id:parsed.data.requestId});}
 else{const linked=ctx.finance.costs.find(c=>c.id===parsed.data.costItemId);if(parsed.data.costItemId&&!linked)return dbError("Custo não encontrado.");const categoryId=linked?.categoryId??parsed.data.categoryId,scopeType=linked?.scopeType??parsed.data.scopeType,scopeId=linked?.stopId??linked?.travelLegId??parsed.data.scopeId;if(!ctx.finance.categories.some(c=>c.id===categoryId&&c.archivedAt===null)||!validScope(scopeType,scopeId,ctx.route))return dbError("Categoria ou associação inválida.");result=await supabase.from("actual_expenses").insert({trip_id:tripId,cost_item_id:linked?.id??null,category_id:categoryId,title:parsed.data.title||null,...scopePayload(scopeType,scopeId),amount_original_minor:mp.original,currency:mp.currency,base_amount_minor:mp.base,conversion_rate:mp.rate,spent_on:parsed.data.date,notes:parsed.data.notes,request_id:parsed.data.requestId});}
 if(result.error?.code!=="23505"&&result.error)return dbError("Não foi possível registar a operação.");revalidatePath(financePath(tripId));redirect(`${financePath(tripId)}?transactionAdded=1`);}

export async function createAdjustmentAction(tripId:string,_state:FinanceActionState,data:FormData):Promise<FinanceActionState>{const parsed=adjustmentSchema.safeParse(fields(data,["paymentId","actualExpenseId","amount","baseAmount","date","notes","requestId"]));if(!parsed.success)return{status:"error",fieldErrors:fieldErrors(parsed.error)};const ctx=await context(tripId);if(!ctx)return dbError("Viagem não encontrada.");const target=parsed.data.paymentId?ctx.finance.payments.find(p=>p.id===parsed.data.paymentId):ctx.finance.actuals.find(a=>a.id===parsed.data.actualExpenseId);if(!target)return dbError("Registo financeiro não encontrado.");const amount=moneyValues({amount:parsed.data.amount,currency:target.currency,baseAmount:parsed.data.baseAmount},ctx.trip.baseCurrency,true);if(!amount)return dbError("O valor do ajuste não é válido.");const mp=moneyPayload(amount),{supabase}=await requireTripUser();const{error}=await supabase.from("financial_adjustments").insert({trip_id:tripId,payment_id:parsed.data.paymentId||null,actual_expense_id:parsed.data.actualExpenseId||null,amount_original_minor:`-${mp.original}`,currency:mp.currency,base_amount_minor:`-${mp.base}`,conversion_rate:mp.rate,adjusted_on:parsed.data.date,notes:parsed.data.notes,request_id:parsed.data.requestId});if(error?.code!=="23505"&&error)return dbError("Não foi possível registar o ajuste.");revalidatePath(financePath(tripId));redirect(`${financePath(tripId)}?transactionAdded=1`);}

export async function createCategoryAction(tripId:string,_state:FinanceActionState,data:FormData):Promise<FinanceActionState>{if(!await getOwnedTrip(tripId))return dbError("Viagem não encontrada.");const parsed=categorySchema.safeParse({name:value(data,"name")});if(!parsed.success)return{status:"error",fieldErrors:fieldErrors(parsed.error)};const{supabase,user}=await requireTripUser();const{error}=await supabase.from("expense_categories").insert({user_id:user.id,name:parsed.data.name});if(error)return dbError(error.code==="23505"?"Já existe uma categoria com este nome.":"Não foi possível criar a categoria.");revalidatePath(financePath(tripId));redirect(`${financePath(tripId)}?categorySaved=1`);}
export async function archiveCategoryAction(tripId:string,categoryId:string,_state:FinanceActionState):Promise<FinanceActionState>{if(!await getOwnedTrip(tripId))return dbError("Viagem não encontrada.");const{supabase,user}=await requireTripUser();const{error}=await supabase.from("expense_categories").update({archived_at:new Date().toISOString()}).eq("id",categoryId).eq("user_id",user.id).eq("is_default",false);if(error)return dbError("Não foi possível desativar a categoria.");revalidatePath(financePath(tripId));redirect(`${financePath(tripId)}?categorySaved=1`);}
