import Link from "next/link";
import { Brand } from "@/components/shared/brand";

export default function HomePage() {
  return <main className="min-h-screen bg-background text-foreground">
    <header className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4 px-6 py-6 sm:px-10"><Brand /><nav aria-label="Conta" className="flex items-center gap-3"><Link href="/auth/sign-in" className="rounded-control px-3 py-2 text-sm text-muted-foreground hover:bg-muted hover:text-foreground">Iniciar sessão</Link><Link href="/auth/sign-up" className="rounded-control border border-border px-4 py-2 text-sm font-medium hover:bg-muted">Criar conta</Link></nav></header>
    <section className="mx-auto grid max-w-7xl items-center gap-14 px-6 py-16 sm:px-10 sm:py-24 lg:grid-cols-[1.1fr_0.9fr] lg:gap-16">
      <div><p className="text-xs font-medium uppercase tracking-[0.16em] text-muted-foreground">Um espaço para a viagem inteira</p><h1 className="mt-6 max-w-2xl text-5xl font-semibold leading-[1.06] tracking-[-0.045em] sm:text-6xl lg:text-7xl">Menos dispersão.<br /><span className="text-muted-foreground">Mais viagem.</span></h1><p className="mt-7 max-w-lg text-base leading-7 text-muted-foreground sm:text-lg sm:leading-8">Junte destinos, orçamento e planos num único lugar. Do primeiro esboço a cada etapa pelo caminho.</p><Link className="mt-8 inline-flex items-center gap-6 rounded-control bg-primary px-5 py-3 text-sm font-medium text-primary-foreground hover:bg-primary-hover" href="/auth/sign-up">Começar a planear <span aria-hidden="true">↗</span></Link></div>
      <figure className="rounded-feature border border-border bg-card p-6 sm:p-8"><figcaption className="flex flex-wrap items-center justify-between gap-3 border-b border-border pb-5"><span className="text-sm font-medium">Uma viagem, várias etapas</span><span className="rounded-control bg-muted px-2 py-1 text-xs text-muted-foreground">Exemplo de rota</span></figcaption><h2 className="mt-7 text-2xl font-semibold tracking-tight">Pela Europa, ao seu ritmo.</h2><p className="mt-2 text-sm text-muted-foreground">Cada destino faz parte da mesma história.</p><ol className="mt-8">{[{ city: "Lisboa", country: "Portugal", leg: "Viagem até Madrid" }, { city: "Madrid", country: "Espanha", leg: "Viagem até Paris" }, { city: "Paris", country: "França", leg: null }].map((stop, index) => <li key={stop.city} className="relative flex gap-4 pb-7 last:pb-0"><div className="flex flex-col items-center"><span className="z-10 flex size-8 items-center justify-center rounded-control border border-border bg-surface text-xs text-muted-foreground">0{index + 1}</span>{stop.leg && <span aria-hidden="true" className="absolute top-8 bottom-0 left-4 border-l border-dashed border-border" />}</div><div className="pt-0.5"><p className="text-sm font-medium">{stop.city}<span className="ml-2 font-normal text-muted-foreground">{stop.country}</span></p>{stop.leg && <p className="mt-5 text-xs text-muted-foreground">{stop.leg}</p>}</div></li>)}</ol><div className="mt-8 flex flex-wrap gap-2 border-t border-border pt-5">{["Rota", "Orçamento", "Itinerário", "Documentos"].map((label) => <span key={label} className="rounded-control border border-border px-2.5 py-1.5 text-xs text-muted-foreground">{label}</span>)}</div></figure>
    </section>
    <section aria-label="O que pode organizar" className="mx-auto max-w-7xl px-6 pb-16 sm:px-10"><div className="grid gap-8 border-t border-border pt-9 md:grid-cols-3">{[{ title: "Todos os destinos, por ordem.", description: "Organize as paragens e os trajetos entre cidades e países, numa rota que faz sentido." }, { title: "As contas, com contexto.", description: "Acompanhe o orçamento, a poupança e os custos da viagem, distinguindo estimativas de valores reais." }, { title: "Tudo pronto para partir.", description: "Reúna o itinerário, as reservas, as listas e os documentos junto dos seus planos." }].map((item, index) => <article key={item.title}><span className="text-xs text-muted-foreground">0{index + 1}</span><h2 className="mt-4 text-base font-semibold">{item.title}</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{item.description}</p></article>)}</div></section>
    <footer className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-3 border-t border-border px-6 py-6 text-xs text-muted-foreground sm:px-10"><span>Triply — cada etapa no seu lugar.</span><Link href="/auth/sign-in" className="hover:text-foreground">Voltar ao meu espaço ↗</Link></footer>
  </main>;
}
