import Link from "next/link";
import { notFound } from "next/navigation";
import { deriveDocumentValidity, expiresDuringTrip, type DocumentValidity } from "@/features/documents/helpers";
import { documentTypeLabels } from "@/features/documents/labels";
import { listOwnedDocuments } from "@/features/documents/queries";
import { getOwnedRoute } from "@/features/route/queries";
import { todayInLisbon } from "@/features/trips/lifecycle";
import { getOwnedTrip } from "@/features/trips/queries";
const validityLabels: Record<DocumentValidity, string> = { expired: "Expirado", expiring_soon: "Expira em breve", valid: "Válido", no_expiry: "Sem validade indicada" }; const first = (v: string | string[] | undefined) => Array.isArray(v) ? v[0] : v;
export default async function DocumentsPage({ params, searchParams }: { params: Promise<{ tripId: string }>; searchParams: Promise<Record<string, string | string[] | undefined>> }) {  
const [{ tripId }, query] = await Promise.all([params, searchParams]); const [trip, documents, route] = await Promise.all([getOwnedTrip(tripId), listOwnedDocuments(tripId), getOwnedRoute(tripId)]); if (!trip || !documents || !route) notFound(); const today = todayInLisbon(), q = (first(query.q) ?? "").toLocaleLowerCase("pt-PT"), type = first(query.type), holder = first(query.holder), stop = first(query.stop), status = first(query.status); const shown = documents.filter(d => !q || `${d.title} ${d.holderLabel ?? ""}`.toLocaleLowerCase("pt-PT").includes(q)).filter(d => !type || d.type === type).filter(d => !holder || d.holderLabel === holder).filter(d => !stop || d.stopId === stop).filter(d => !status || deriveDocumentValidity(d.expiryDate, today) === status).sort((a, b) => rank(deriveDocumentValidity(a.expiryDate, today)) - rank(deriveDocumentValidity(b.expiryDate, today))); const holders = [...new Set(documents.map(d => d.holderLabel).filter((x): x is string => Boolean(x)))].sort(); return (
    <main className="min-h-screen bg-background px-5 py-8 sm:px-8 lg:px-12"><div className="mx-auto max-w-6xl"><Link href={`/trips/${tripId}`}>← Voltar à viagem</Link>
      <header className="my-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-muted-foreground">Documentos privados</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Documentos de {trip.name}</h1><p className="mt-2 text-muted-foreground">Organize metadados e ficheiros privados sem guardar identificadores sensíveis desnecessários.</p></div><Link href={`/trips/${tripId}/documents/new`} className="rounded-control bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground">Adicionar documento</Link></header>

      <form className="grid gap-3 rounded-card border border-border bg-surface p-5 sm:grid-cols-2 xl:grid-cols-4"><input name="q" defaultValue={q} placeholder="Pesquisar título ou titular" aria-label="Pesquisar documentos" className="h-11 min-w-0 rounded-control border border-input bg-background px-3 sm:col-span-2 xl:col-span-4" /><Filter name="type" label="Todos os tipos" value={type} items={Object.entries(documentTypeLabels)} /><Filter name="holder" label="Todos os titulares" value={holder} items={holders.map(x => [x, x])} /><Filter name="stop" label="Todos os destinos" value={stop} items={route.stops.map(x => [x.id, x.placeName])} /><Filter name="status" label="Todos os estados" value={status} items={Object.entries(validityLabels)} /><button className="min-h-11 rounded-control border border-input bg-card px-4 py-2 text-sm font-semibold hover:bg-muted sm:col-span-2 xl:col-span-4 xl:justify-self-end">Aplicar filtros</button></form>

      <section className="mt-8 grid gap-5 md:grid-cols-2">{shown.map(document => { const validity = deriveDocumentValidity(document.expiryDate, today), during = expiresDuringTrip(document, trip.endDate); return <article key={document.id} className="flex flex-col rounded-card border border-border bg-card p-6 sm:p-7"><div className="flex flex-wrap justify-between gap-2"><p className="text-xs font-semibold uppercase text-muted-foreground">{documentTypeLabels[document.type]}</p><span className="rounded-control bg-muted px-3 py-1 text-xs font-semibold">{validityLabels[validity]}</span></div><h2 className="mt-3 text-xl font-semibold">{document.title}</h2><p className="mt-2 text-sm text-muted-foreground">{document.holderLabel ? `Titular: ${document.holderLabel} · ` : ""}{document.attachmentPath ? "Ficheiro disponível" : "Sem ficheiro"}</p><div className="pb-6">{during ? <p role="status" className="mt-3 font-semibold text-warning">Atenção: expira antes do fim da viagem. Confirme os requisitos oficiais aplicáveis.</p> : null}{document.needsReview ? <p role="status" className="mt-3 font-semibold text-warning">Rever associação: o item relacionado foi alterado ou removido.</p> : null}</div><div className="mt-auto flex flex-wrap gap-5 border-t border-border pt-5"><Link href={`/trips/${tripId}/documents/${document.id}/edit`} className="text-sm font-semibold underline">Editar</Link>{document.attachmentPath ? <a href={`/trips/${tripId}/documents/${document.id}/download`} className="text-sm font-semibold underline">Abrir ficheiro</a> : null}</div></article> })}{!shown.length ? <div className="rounded-feature border border-dashed border-input bg-card p-10 text-center md:col-span-2"><h2 className="text-xl font-semibold">{documents.length ? "Nenhum documento corresponde aos filtros" : "Ainda não existem documentos"}</h2><p className="mt-2 text-muted-foreground">Pode começar por um passaporte, seguro, visto ou voucher quando for relevante.</p><Link href={`/trips/${tripId}/documents/new`} className="mt-5 inline-block rounded-control bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground">Adicionar documento</Link></div> : null}</section>
    </div></main>
  );
}
function Filter({ name, label, value, items }: { name: string; label: string; value?: string; items: [string, string][] }) { return <select name={name} defaultValue={value ?? ""} aria-label={label} className="h-11 min-w-0 rounded-control border border-input bg-background px-3"><option value="">{label}</option>{items.map(([id, text]) => <option key={id} value={id}>{text}</option>)}</select> } function rank(v: DocumentValidity) { return v === "expired" ? 0 : v === "expiring_soon" ? 1 : v === "valid" ? 2 : 3 }
