import Link from "next/link";
import { notFound } from "next/navigation";
import { RouteOverview } from "@/features/route/components/overview";
import { TripDashboard } from "@/features/dashboard/components/trip-dashboard";
import { getTripDashboard } from "@/features/dashboard/queries";
import { DeleteTripForm, TripLifecycleAction } from "@/features/trips/components/trip-actions";
import { todayInLisbon } from "@/features/trips/lifecycle";
import { tripIdSchema } from "@/features/trips/schemas";

export default async function TripPage({params}:{params:Promise<{tripId:string}>}){const{tripId}=await params;if(!tripIdSchema.safeParse(tripId).success)notFound();const dashboard=await getTripDashboard(tripId,todayInLisbon());if(!dashboard)notFound();return <main className="min-h-screen bg-background px-5 py-8 text-foreground sm:px-8"><div className="mx-auto max-w-6xl"><div className="mb-6 flex flex-wrap items-center justify-between gap-4"><Link href="/trips" className="text-sm font-medium text-muted-foreground hover:text-foreground">← Todas as viagens</Link><div className="flex flex-wrap gap-3"><Link href={`/trips/${tripId}/settings`} className="rounded-full border border-input bg-card px-5 py-2.5 text-sm font-semibold">Definições</Link><Link href={`/trips/${tripId}/edit`} className="rounded-full border border-input bg-card px-5 py-2.5 text-sm font-semibold">Editar viagem</Link></div></div><TripDashboard dashboard={dashboard} today={todayInLisbon()}/><div id="route" className="scroll-mt-6">{dashboard.route.status === "ready" ? <RouteOverview trip={dashboard.trip} route={dashboard.route.data} /> : <p role="alert" className="mt-8 rounded-card border border-destructive bg-destructive-muted p-5 text-destructive">Não foi possível carregar a rota. Atualize a página para tentar novamente.</p>}</div><section aria-labelledby="management-title" className="mt-12 border-t border-border pt-8"><h2 id="management-title" className="text-xl font-semibold">Gerir viagem</h2><div className="mt-5 space-y-5"><TripLifecycleAction tripId={tripId} archived={dashboard.trip.archivedAt!==null}/><DeleteTripForm tripId={tripId} tripName={dashboard.trip.name}/></div></section></div></main>}
